# Uncomment the next line to define a global platform for your project

source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'

target 'iOSAbility' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  pod 'Masonry'
  pod 'ReactiveObjC'
  pod 'SDWebImage'

end

post_install do |installer_or_rep|
  installer = installer_or_rep.respond_to?(:installer) ? installer_or_rep.installer : installer_or_rep
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      target.build_settings(configuration.name)['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
